# Generated by Django 5.2.7 on 2025-10-07 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='espece',
            name='nom_3',
        ),
        migrations.RemoveField(
            model_name='espece',
            name='nom_sic',
        ),
        migrations.AddField(
            model_name='espece',
            name='status',
            field=models.CharField(choices=[('lr', "Pas en voie d'extinction"), ('hr', "En voie d'extinction"), ('extinct', "Y'en a plus"), ('default', 'default')], default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='espece',
            name='nom',
            field=models.CharField(default='espece inconnu', max_length=255),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_observation', models.DateTimeField()),
                ('quantite', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='faunatrack.espece')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faunatrack.location')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faunatrack.project')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, null=True, upload_to='photos_obs/')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='faunatrack.observation')),
            ],
        ),
        migrations.CreateModel(
            name='Scientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
