# Generated by Django 5.2.7 on 2025-10-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0002_location_project_remove_espece_nom_3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espece',
            options={'ordering': ['nom'], 'verbose_name': 'Espece', 'verbose_name_plural': 'Espèces'},
        ),
        migrations.AlterModelOptions(
            name='observationphotos',
            options={'ordering': ['observation'], 'verbose_name': "Photo d'observation", 'verbose_name_plural': "Photos d'observations"},
        ),
        migrations.AlterField(
            model_name='espece',
            name='nom',
            field=models.CharField(default='espece inconnu', max_length=255, unique=True),
        ),
    ]
