# Generated by Django 5.2.7 on 2025-10-08 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0003_alter_espece_options_alter_observationphotos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientifique',
            name='roles',
        ),
        migrations.CreateModel(
            name='ProjectsMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.CharField(choices=[('admin', 'administrateur'), ('member', 'member')], default='member', max_length=255)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member', to='faunatrack.project')),
                ('scientifique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_member', to='faunatrack.scientifique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scientifique',
            name='projets',
            field=models.ManyToManyField(through='faunatrack.ProjectsMembers', to='faunatrack.project'),
        ),
    ]
