# Generated by Django 5.2.7 on 2025-10-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0004_remove_scientifique_roles_projectsmembers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='faunatrack.project'),
        ),
    ]
