# Generated by Django 5.2.7 on 2025-10-10 13:37

from django.db import migrations

def my_function(apps, schema_editor):
    pass

def my_function_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0005_alter_observation_notes_alter_observation_project'),
    ]

    operations = [
        migrations.RunPython(my_function, my_function_reverse)
    ]
